CTP_PROJECT_KEY: 
CTP_CLIENT_SECRET: 
CTP_CLIENT_ID: 
CTP_AUTH_URL: "https://auth.us-central1.gcp.commercetools.com"
CTP_API_URL: "https://api.us-central1.gcp.commercetools.com"
CTP_SCOPES: 

CTP_PRODUCT_STATE_TRIGGER: product-ready-for-magic
CTP_PRODUCT_STATE_TRANSITION: product-description-updated
CTP_PRODUCT_STATE_TRANSITION_ID: f6e25138-ba74-462a-8e5c-b22b846a3d22

OPENAI_API_KEY: 

SEED_TEXT_EXPERT: "Product name: Kangra Sweater\nSeed words: grey, sweater, v-neck, casual, long-sleeve, everday, business casual, comfortable, ribbed cuffs and hem\nTone: Expert\nProduct description: This grey long-sleeve sweater is a classic wardrobe staple with traditional details, like a v-neck, and ribbed texture at the cuffs and hem."
SEED_TEXT_SOPHISTICATED: "Product name: Kangra Sweater\nSeed words: grey, sweater, v-neck, casual, long-sleeve, everday, business casual, comfortable, ribbed cuffs and hem\nTone: Sophisticated\nProduct description: This cozy grey long-sleeve v-neck sweater is the perfect piece for everyday use.  It easily transitions from home to office to a night on the town."